// IRA · Metodología 2.0 · P1 La frontera del nosotros · textos de la página.
// Fuente única: research/manual/P1.md (v1.1). Aquí solo se resume, se reordena y se adapta el
// tono: no se añaden reglas, autores ni cifras que no estén en el manual.
// La versión inglesa está pendiente de revisión del autor.

const REFERENCIAS = [
  'Avenanti, A., Sirigu, A., y Aglioti, S. M. (2010). Racial bias reduces empathic sensorimotor resonance with other-race pain. Current Biology, 20(11), 1018–1022.',
  'Chilton, P. (2004). Analysing political discourse: Theory and practice. Routledge.',
  'Gaertner, S. L., y Dovidio, J. F. (2000). Reducing intergroup bias: The common ingroup identity model. Psychology Press.',
  'Gallese, V. (2001). The "shared manifold" hypothesis: From mirror neurons to empathy. Journal of Consciousness Studies, 8(5–7), 33–50.',
  'Gallese, V. (2003). The roots of empathy: The shared manifold hypothesis and the neural basis of intersubjectivity. Psychopathology, 36(4), 171–180.',
  'Hein, G., Silani, G., Preuschoff, K., Batson, C. D., y Singer, T. (2010). Neural responses to ingroup and outgroup members\' suffering predict individual differences in costly helping. Neuron, 68(1), 149–160.',
  'Huddy, L., y Yair, O. (2021). Reducing affective polarization: Warm group relations or policy compromise? Political Psychology, 42(2), 291–309.',
  'Laclau, E. (2005). La razón populista. Fondo de Cultura Económica.',
  'Mouffe, C. (2005). On the political. Routledge.',
  'Rathje, S., Van Bavel, J. J., y van der Linden, S. (2021). Out-group animosity drives engagement on social media. PNAS, 118(26), e2024292118.',
  'Reisigl, M., y Wodak, R. (2001). Discourse and discrimination. Routledge.',
  'Tajfel, H., y Turner, J. C. (1979). An integrative theory of intergroup conflict. En W. G. Austin y S. Worchel (Eds.), The social psychology of intergroup relations (pp. 33–47). Brooks/Cole.',
  'van Dijk, T. A. (2006). Ideology and discourse analysis. Journal of Political Ideologies, 11(2), 115–140.',
  'Xu, X., Zuo, X., Wang, X., y Han, S. (2009). Do you feel my pain? Racial group membership modulates empathic neural responses. The Journal of Neuroscience, 29(26), 8525–8529.',
];

export const TEXTOS_P1 = {
  es: {
    volverIndice: '← Metodología 2.0',
    rotulo: 'Parámetro 1 · manual v1.1',
    titulo: 'La frontera del nosotros',
    indiceTitulo: 'En esta página',
    indiceDesplegar: 'Ir a una sección',
    pieza: 'Pieza interactiva en construcción',

    secciones: [
      { id: 'en-una-frase', titulo: 'En una frase' },
      { id: 'mapa', titulo: 'El mapa de la frontera' },
      { id: 'que-mide', titulo: 'Qué mide y por qué' },
      { id: 'que-no-mide', titulo: 'Qué no mide P1' },
      { id: 'como-se-aplica', titulo: 'Cómo se aplica' },
      { id: 'discurso-anotado', titulo: 'El discurso anotado' },
      { id: 'indicadores', titulo: 'Los tres indicadores' },
      { id: 'ficha', titulo: 'La ficha' },
      { id: 'excepcion', titulo: 'La excepción democrática' },
      { id: 'cuenta-o-no', titulo: '¿Cuenta o no?' },
      { id: 'minimos', titulo: 'Mínimos y solidez' },
      { id: 'limites', titulo: 'Límites y trabajo pendiente' },
      { id: 'cambios', titulo: 'Registro de cambios' },
      { id: 'referencias', titulo: 'Referencias' },
    ],

    frase: 'P1 mide dónde traza el discurso la línea entre «nosotros» y «ellos», y si esa línea es un muro o una puerta.',
    formula: ['P1 = 0,50 × Alcance', '   + 0,28 × Permeabilidad', '   + 0,22 × Interpelación'],
    formulaNota: 'Si algún indicador no llega a su mínimo, su peso se reparte en proporción entre los demás.',

    piezas: {
      mapa: 'Un mapa con el nosotros en el centro y cuatro frases para probar: cómo cada una abre una puerta, levanta un muro o amplía el círculo.',
      anotado: 'Un fragmento del discurso de Pedro Sánchez en Barcelona (2026) con cada referencia a personas marcada según su categoría.',
      ficha: 'La ficha de P1 de dos discursos, Barcelona y la ONU, con el cálculo paso a paso.',
      arbol: 'El árbol de decisión de la excepción democrática, con las frases de ejemplo del manual.',
      juego: 'Un juego corto con los casos resueltos del manual: ¿cuenta o no?',
    },

    que: {
      intro: [
        'Antes de cualquier argumento, el lenguaje decide quién está dentro y quién fuera. El pronombre coloca al oyente en un lugar: dentro del círculo del hablante, en su periferia o frente a él.',
        'Esa colocación ocurre de forma prerreflexiva: el oyente se siente incluido o excluido antes de pensarlo.',
      ],
      teoriaTitulo: 'Base teórica',
      teoria: [
        { autor: 'Gallese (2001, 2003)', texto: 'La empatía es resonancia intersubjetiva: el múltiple compartido (shared manifold) permite simular al otro de forma encarnada y prerreflexiva. La neurociencia del sesgo empático intergrupal (Xu et al., 2009; Avenanti et al., 2010; Hein et al., 2010) muestra que esa resonancia se debilita cuando el otro es categorizado como exogrupo, y se recupera en parte cuando es individualizado o recategorizado como «uno de los nuestros».' },
        { autor: 'Chilton (2004)', texto: 'El discurso construye un espacio deíctico con un centro (yo, nosotros, aquí, ahora, lo correcto) y una periferia. La deixis pronominal es un acto de posicionamiento político.' },
        { autor: 'Van Dijk (1998, 2006)', texto: 'El cuadrado ideológico: realzar lo bueno nuestro y lo malo de ellos.' },
        { autor: 'Mouffe (2005)', texto: 'El adversario legítimo sigue dentro del espacio común; el enemigo queda fuera. La democracia necesita frontera, pero agonista, no antagonista.' },
        { autor: 'Laclau (2005)', texto: 'La frontera entre «el pueblo» y su otro es literal y constitutiva. Su polo opuesto se nombra a menudo con palabras abstractas que designan personas.' },
        { autor: 'Tajfel y Turner (1979); Gaertner y Dovidio (2000)', texto: 'La categorización activa el favoritismo endogrupal; la recategorización en un nosotros común lo reduce.' },
      ],
      cautelaTitulo: 'Cautela',
      cautela: 'P1 no mide la resonancia neural de la audiencia. Es un indicador discursivo de las condiciones de categorización que la neurociencia asocia con esa resonancia.',
    },

    noMide: {
      cabecera: ['Fenómeno', 'Dónde se mide'],
      filas: [
        { fenomeno: 'Verbos bélicos («derrotar», «luchar»)', destino: ['P2', 'P6'], nota: 'metáfora y acción' },
        { fenomeno: 'Marcos de competición («victoria», «batalla»)', destino: ['P2'] },
        { fenomeno: 'Juicio moral sobre el adversario («corruptos», «malvados»)', destino: ['P3'] },
        { fenomeno: 'Deshumanización («plaga», «virus»)', destino: ['P2', 'P3'], nota: 'en P1 solo cuenta como un cierre más' },
        { fenomeno: 'Emociones movilizadas', destino: ['P4'] },
        { fenomeno: 'Acciones coercitivas («doblarles el brazo»)', destino: ['P6'] },
        { fenomeno: 'El «yo» del hablante (distancia vertical con el público)', destino: ['P8'], nota: 'no puntúa en P1; candidato a P8' },
      ],
      regla: 'Regla general: P1 registra dónde se traza la línea, no lo que se dice de quien queda al otro lado.',
    },

    aplica: {
      pasos: [
        { nombre: 'Extraer', quien: 'Código', texto: 'Un script saca todas las referencias a personas: pronombres, desinencias verbales de 1.ª y 2.ª persona, posesivos y clíticos, con su oración. Es determinista: el mismo texto da siempre la misma tabla.' },
        { nombre: 'Revisar', quien: 'Humano, 5 minutos', texto: 'El extractor acierta en torno a 9 de cada 10. Los errores típicos (persona mal asignada, sustantivos tomados por verbos, clíticos pegados omitidos, sujetos contados dos veces) se marcan, y las omisiones se añaden a mano.' },
        { nombre: 'Clasificar', quien: 'Humano o IA', texto: 'Cada referencia recibe un código del manual. Los eventos de frontera se anotan en una tabla aparte.' },
        { nombre: 'Calcular', quien: 'Código', texto: 'Un script aplica las fórmulas y escribe la ficha.' },
      ],
      clave: 'La IA nunca pone la nota: clasifica, y las fórmulas calculan.',
      reproducibilidad: 'Versión 1.1 probada con spaCy 3.8.16 y el modelo es_core_news_md 3.8.0. Cualquier cambio de versión del software, del modelo de IA o del manual se anota en la ficha, porque puede cambiar los resultados.',
    },

    ind: {
      queMide: 'Qué mide',
      unidad: 'Unidad',
      formula: 'Fórmula',
      reglas: 'Reglas',
      codigo: 'Código',
      categoria: 'Categoría',
      valor: 'Valor',
      ejemplos: 'Ejemplos',
      noCuenta: 'no cuenta',
      alcance: {
        nombre: 'Alcance del nosotros',
        peso: '50 %',
        queMide: 'Cuántos de los «nosotros» del discurso se construyen contra alguien.',
        unidad: 'Cada mención de primera persona del plural (pronombre, desinencia verbal o posesivo).',
        codigos: [
          { codigo: 'U', categoria: 'Universal sin oposición', valor: '10', ej: '«nuestros hijos», «nuestras democracias», «no podemos volver a la situación anterior» (dicho a toda la comunidad internacional)' },
          { codigo: 'G', categoria: 'Grupo sin perdedor', valor: '10', ej: '«en este lugar somos 5.000 personas soñando un mundo mejor», «estamos aquí para celebrar nuestra unidad»' },
          { codigo: 'GC', categoria: 'Contra alguien (de grupo o universal)', valor: '0', ej: '«la vergüenza para ellos; para nosotros el orgullo», «vamos a reconstruir lo que ellos han tratado de destruir», «el pueblo frente a la casta», «los tecnoligarcas se llenan el bolsillo a costa de nuestras democracias»' },
          { codigo: 'S', categoria: 'Situacional', valor: null, ej: '«los líderes que nos acompañan aquí»' },
          { codigo: 'I', categoria: 'Institucional', valor: null, ej: '«desde España condenamos», «estamos aprobando una regularización»' },
          { codigo: 'A', categoria: 'Ambiguo', valor: null, ej: 'No se puede decidir con el contexto disponible.' },
          { codigo: 'X', categoria: 'Error de extracción', valor: null, ej: '' },
          { codigo: 'Y', categoria: 'Primera persona singular («yo», «me», «mi»)', valor: null, ej: 'Se registra para un futuro P8.' },
          { codigo: 'F', categoria: 'Tercera persona «ellos»', valor: null, ej: 'La frontera que marca se anota como evento en la permeabilidad.' },
        ],
        reglas: [
          '«Contra alguien» manda sobre el alcance. Cualquier nosotros, de grupo o universal, que en su oración se construye frente a un otro identificable es GC. Es la frontera populista de Laclau: «el pueblo» contra «la casta» es universal en la forma y excluyente en la función. Solo se libra por la excepción democrática.',
          'El perdedor tiene que estar en el texto. Un nosotros es GC solo si el otro es identificable: nombrado («la derecha») o recuperable del contexto inmediato («ellos», «quienes nos critican»). Si el perdedor solo está implícito en una metáfora («esta victoria es vuestra»), es G, y el marco competitivo lo recoge P2.',
          'El grupo cálido es inclusivo. Hablar a los propios sin invalidar a nadie no levanta ningún muro, por eso G vale lo mismo que U. Lo que distingue a un discurso que abre la frontera a toda la sociedad se recoge en la permeabilidad.',
          'La oración es el contexto. La clasificación se decide mirando la oración que contiene la mención y, si hace falta, la anterior.',
          'Situacional es el nosotros que solo señala a quienes están físicamente presentes. No es ni bueno ni malo.',
        ],
        formula: 'Alcance = 10 × (U + G) / (U + G + GC)',
      },
      interpelacion: {
        nombre: 'Interpelación',
        peso: '22 %',
        queMide: 'Cómo se dirige el discurso a su público con la segunda persona.',
        unidad: 'Cada mención de segunda persona (tú, usted, ustedes, vosotros; sus desinencias, posesivos y clíticos).',
        codigos: [
          { codigo: '2I', categoria: 'Inclusiva', ej: '«gracias por llenar este espacio con vuestra ilusión», «os pido que hagamos realidad nuestros sueños»' },
          { codigo: '2C', categoria: 'Contra alguien', ej: '«os pido que no os engañen» (supone a alguien que engaña), «ustedes, los de siempre»' },
        ],
        regla: 'La calidez hacia el propio público es inclusiva salvo que la oración invalide o ataque a otro. Es la misma lógica que el alcance, incluida la excepción democrática.',
        formula: 'Interpelación = 10 × 2I / (2I + 2C)',
      },
      permeabilidad: {
        nombre: 'Permeabilidad',
        peso: '28 %',
        queMide: 'Si la frontera es un muro o una puerta: si el otro puede llegar a formar parte del nosotros.',
        unidad: 'El evento de frontera: cada oración en la que el discurso coloca a un otro humano identificable respecto al nosotros. Una oración con dos referentes distintos genera dos eventos. Un mismo referente con varias marcas en la misma oración es un solo evento.',
        blancosTitulo: '¿Quién queda fuera? Tipos de blanco',
        blancosCabecera: ['Blanco', 'Ejemplo', '¿Es frontera?'],
        blancos: [
          { blanco: 'Un problema', ej: '«acabar con la pobreza», «la corrupción»', frontera: 'No', es: false },
          { blanco: 'Una política', ej: '«esta reforma laboral es injusta»', frontera: 'No', es: false },
          { blanco: 'Una ideología', ej: '«el neoliberalismo ha fracasado»', frontera: 'Solo si se le da cuerpo: se la presenta como agente hostil («el comunismo quiere destruir vuestras familias») o se extiende a sus portadores', es: null },
          { blanco: 'Personas con nombre de estructura', ej: '«la casta», «las élites», «el régimen», «los de arriba»', frontera: 'Sí', es: true },
          { blanco: 'La casa común (instituciones democráticas)', ej: '«los jueces son golpistas», «las elecciones están amañadas»', frontera: 'Sí. Criticar cómo funciona una institución («la justicia es lenta») no lo es; deslegitimarla, sí', es: true },
        ],
        marcasTitulo: 'Marcas de cierre y de apertura',
        marcasNota: 'Todas las marcas valen 1.',
        cierresTitulo: 'Cierres (C) · 7 marcas',
        cierres: [
          ['C1', 'Contraposición nosotros/ellos', '«la vergüenza para ellos; para nosotros el orgullo»'],
          ['C2', 'Bloque homogéneo', '«todos son iguales», una lista de conductas fundida en un solo «ellos»'],
          ['C3', 'Irreversibilidad', '«son así y no van a cambiar», «jamás serán de los nuestros»'],
          ['C4', 'Expulsión de la comunidad', '«no son el pueblo», «antiespañoles»'],
          ['C5', 'Amenaza dirigida al nosotros', '«vienen a por nosotros», «han intentado que nos avergoncemos»'],
          ['C6', 'Deshumanización', '«una plaga», «ratas»'],
          ['C7', 'Negación de la palabra', '«con esa gente no se habla»'],
        ],
        aperturasTitulo: 'Aperturas (A) · 9 marcas',
        aperturas: [
          ['A1', 'Invitación', '«también a quienes no nos votaron»'],
          ['A2', 'Separar dirigentes y gente', 'distinguir la decisión de un gobierno de su pueblo'],
          ['A3', 'Pertenencia común con diferencia', '«pensamos distinto, pero también son de aquí», «they are us»'],
          ['A4', 'Adversario legítimo', '«respeto a quien defiende otra opción»'],
          ['A5', 'Humanizar a alguien del otro lado', 'nombrar a una persona concreta con su historia'],
          ['A6', 'Reconocer un acierto o autocrítica', '«en eso acertaron», «también nos equivocamos»'],
          ['A7', 'Destino compartido', '«esto nos afecta a todos, pensemos lo que pensemos»'],
          ['A8', 'Negar un cierre', '«no son enemigos»'],
          ['A9', 'Inclusión condicionada', '«los que rectifiquen serán bienvenidos»'],
        ],
        dificilesTitulo: 'Casos difíciles',
        dificiles: [
          ['Discurso referido', '«Dicen que somos antiespañoles» no es un cierre del hablante. Si lo rechaza explícitamente, puede ser A8.'],
          ['Ironía', 'Se codifica según la intención clara del contexto; si hay duda, no se codifica.'],
          ['Marca mixta', '«Sus dirigentes nos traicionaron, pero sus votantes son gente honrada» son dos eventos: un cierre (dirigentes) y una apertura A2 (votantes).'],
          ['Interpelar al adversario', '«Le quiero decir a la derecha...» no es cierre por sí mismo: le habla, no lo expulsa. Lo que diga de él lo mide P3.'],
        ],
        formula: 'Permeabilidad = 10 × (A + 1) / (A + C + 2)',
        formulaNombre: 'Regla de sucesión de Laplace',
        formulaNota: 'Sin eventos, la permeabilidad no se puntúa. Con pocos eventos, la fórmula acerca la nota al centro para que un solo evento no la dispare.',
      },
    },

    excepcion: {
      intro: 'El IRA está contra la violencia, no contra quien la nombra. Una frontera trazada frente a alguien por su conducta violenta o antidemocrática no penaliza: en la permeabilidad se registra como CP y no puntúa; en el alcance y la interpelación, el nosotros o la segunda persona conserva su categoría normal (U, G, 2I) con la nota «excepción democrática».',
      verdad: 'El IRA no decide si la acusación es verdad. Por eso la excepción depende de cómo se traza la frontera, no de quién tiene razón. Se aplica solo si la oración cumple las tres condiciones:',
      condiciones: [
        ['Conducta concreta', 'Al otro se le identifica por un acto («atacó», «invadió», «asesinó», «anuló las elecciones»), no por lo que es.'],
        ['Agente acotado', 'El acto se atribuye a quien lo cometió: una persona, un gobierno, un grupo armado, «quienes hicieron esto». Nunca a un pueblo, una etnia, una religión o los votantes de un partido.'],
        ['Sin extensión', 'En esa oración no se generaliza («todos», «siempre»), no se esencializa («son así») ni se deshumaniza.'],
      ],
      falla: 'Si falla cualquiera, es un cierre normal (y el nosotros, GC).',
      ejemplosCabecera: ['Oración', '¿Excepción?'],
      ejemplos: [
        ['«El terrorista atacó a nuestra comunidad»', true, 'acto concreto, agente individual'],
        ['«Rusia ha invadido nuestro país»', true, 'acto concreto, el Estado como actor'],
        ['«El régimen de Kiev atacó a nuestro pueblo»', true, 'formalmente idéntica a la anterior'],
        ['«El gobierno de X está cometiendo un genocidio»', true, 'agente acotado'],
        ['«Los X son genocidas»', false, 'un pueblo entero'],
        ['«Los ucranianos son nazis que nos odian»', false, 'un pueblo entero, esencializado'],
        ['«Los inmigrantes traen la violencia a nuestros barrios»', false, 'habla de violencia, pero contra un grupo por lo que es'],
        ['«No pactaremos con quien justifique la violencia»', true, 'aplicable a cualquiera, también a los propios'],
      ],
      si: 'Sí', no: 'No',
      salvaguardasTitulo: 'Dos salvaguardas',
      salvaguardas: [
        ['Aviso en la ficha', 'Cada excepción aplicada aparece listada en la ficha con la frase, bajo el aviso «el IRA no verifica estas acusaciones», para que el lector sepa dónde el análisis ha confiado en la palabra del orador.'],
        ['Retirada por desmentido documentado', 'Si una verificación independiente y publicada (un verificador acreditado por la red IFCN, como Maldita, Newtral o EFE Verifica) desmiente la acusación, la excepción se retira y la oración cuenta como cierre normal: inventarse un agresor para trazar una frontera es fabricar un enemigo. La fuente se cita en la ficha. Sin desmentido documentado, se mantiene la excepción con su aviso.'],
      ],
    },

    minimos: {
      cabecera: ['Indicador', 'Peso', 'Mínimo para puntuar'],
      filas: [
        ['Alcance', '50 %', '15 nosotros clasificables (U + G + GC)'],
        ['Permeabilidad', '28 %', '3 eventos (A + C)'],
        ['Interpelación', '22 %', '3 menciones (2I + 2C)'],
      ],
      notas: [
        'Si un indicador no llega al mínimo, su peso se reparte en proporción entre los demás.',
        'P1 se puntúa si el alcance o la permeabilidad llegan a su mínimo. Así, un discurso que polariza casi todo en tercera persona («ellos roban, ellos mienten») no se queda sin nota: la saca sobre todo de la permeabilidad.',
        'Solidez de P1. Si el alcance llega al mínimo: de 15 a 40 nosotros clasificables, orientativa; más de 40, sólida. Si solo puntúa la permeabilidad: de 3 a 5 eventos, orientativa; 6 o más, sólida. Si no llega ninguno: sin puntuar.',
        'Repeticiones. Cada mención y cada evento cuentan, aunque se repitan, y una misma oración puede restar en el alcance y en la permeabilidad: cada indicador mide una propiedad distinta de la frase.',
        'La extensión mínima se expresa en referencias, no en palabras: un mitin puede tener 40 nosotros por cada mil palabras y una intervención institucional, 14.',
      ],
    },

    limites: [
      ['«Ustedes» en América', 'Es tercera persona gramaticalmente y el extractor solo busca 1.ª y 2.ª. Hay que añadirlo antes de analizar el corpus latinoamericano. «Les» también es ambiguo.'],
      ['El adversario nombrado', 'El extractor solo capta «ellos»; los grupos nominales («la derecha», «los tecnoligarcas») y los sujetos implícitos («han intentado que...») los encuentra el codificador al anotar los eventos. Pendiente: proponerlos automáticamente.'],
      ['Acusaciones falsas bien formuladas', 'Una acusación de violencia falsa que cumple las tres condiciones de la excepción pasa el filtro mientras no exista un desmentido documentado. El IRA mide el lenguaje, no los hechos; la ficha lo avisa y la verificación corresponde al periodismo.'],
      ['Discursos con pocos eventos pero intensos', 'La ONU tiene dos cierres claros («gente sin escrúpulos, activistas de la mentira») y queda sin puntuar por el mínimo de 3.'],
      ['Traducciones', 'P1 no se aplica a discursos traducidos: el pronombre lo elige el traductor. Para inglés haría falta un extractor propio.'],
      ['Género discursivo', 'Mitin, intervención institucional, entrevista y redes deben anotarse para comparar dentro del mismo género.'],
      ['Pesos e intensidades', 'Los pesos (50/28/22) y el valor 1 de todas las marcas son hipótesis: se calibrarán con el corpus.'],
      ['Fiabilidad', 'Falta el estudio intercodificadores (α de Krippendorff ≥ 0,80 en códigos y eventos) y la comparación humano frente a IA.'],
      ['Solapamiento entre indicadores', 'Si con más discursos el alcance y la permeabilidad resultaran ir siempre juntos, uno de los dos sobraría y P1 podría simplificarse. No es un error, sino una posible simplificación futura.'],
    ],

    cambios: {
      fecha: '9 de octubre de 2026',
      v1: {
        titulo: 'Versión 1',
        decisiones: [
          'P1 pasa a ser puramente deíctico: los verbos que acompañan al pronombre salen de P1 (van a P2 y P6).',
          'Recuento por código (spaCy y léxico fijo) y clasificación por humano o IA; el cálculo, siempre por código.',
          'Umbrales de solidez: menos de 15 nosotros, no fiable; de 15 a 40, orientativa; más de 40, sólida.',
          'El nosotros de grupo sin perdedor vale 10, igual que el universal; solo el nosotros contra alguien vale 0.',
          'El perdedor implícito en una metáfora no convierte el nosotros en «contra alguien»: lo mide P2.',
          'Nueva categoría situacional, fuera del cálculo.',
          'El «yo» sale de P1; candidato a P8 cuando se pueda codificar con marcas observables.',
          'Interpelación: la calidez hacia el propio público es inclusiva salvo que ataque o invalide a otro.',
          'Permeabilidad por eventos observables; fórmula de Laplace; mínimo de 3 eventos.',
          'Tipos de blanco: problemas y políticas no son frontera; ideologías solo con cuerpo; personas con nombre de estructura y deslegitimar la casa común, sí.',
          'Excepción democrática: la frontera por conducta violenta o antidemocrática no puntúa.',
          'Todas las marcas de cierre y apertura valen 1 en esta versión.',
        ],
      },
      v11: {
        titulo: 'Versión 1.1',
        decisiones: [
          '«Contra alguien» manda sobre el alcance: el nosotros universal construido frente a un otro identificable es GC.',
          'P1 se puntúa si el alcance o la permeabilidad llegan a su mínimo.',
          'Las repeticiones y las oraciones que restan en dos indicadores cuentan cada vez: cada indicador mide una propiedad distinta.',
          'La excepción democrática se aplica a todo P1, con tres condiciones (conducta concreta, agente acotado, sin extensión) que no dependen de la verdad de la acusación.',
          'Cada excepción se señala en la ficha; se retira si un verificador acreditado la desmiente con fuente publicada.',
        ],
      },
    },

    referencias: REFERENCIAS,
    manual: 'Manual completo de P1 en el repositorio',
    pie: { volver: '← Volver al índice', siguiente: 'Siguiente: P2 · próximamente' },
  },

  en: {
    volverIndice: '← Methodology 2.0',
    rotulo: 'Parameter 1 · manual v1.1',
    titulo: 'The boundary of "us"',
    indiceTitulo: 'On this page',
    indiceDesplegar: 'Jump to a section',
    pieza: 'Interactive piece under construction',

    secciones: [
      { id: 'en-una-frase', titulo: 'In one sentence' },
      { id: 'mapa', titulo: 'The boundary map' },
      { id: 'que-mide', titulo: 'What it measures and why' },
      { id: 'que-no-mide', titulo: 'What P1 does not measure' },
      { id: 'como-se-aplica', titulo: 'How it is applied' },
      { id: 'discurso-anotado', titulo: 'The annotated speech' },
      { id: 'indicadores', titulo: 'The three indicators' },
      { id: 'ficha', titulo: 'The scorecard' },
      { id: 'excepcion', titulo: 'The democratic exception' },
      { id: 'cuenta-o-no', titulo: 'Does it count?' },
      { id: 'minimos', titulo: 'Minimums and robustness' },
      { id: 'limites', titulo: 'Limitations and pending work' },
      { id: 'cambios', titulo: 'Change log' },
      { id: 'referencias', titulo: 'References' },
    ],

    frase: 'P1 measures where a speech draws the line between "us" and "them", and whether that line is a wall or a door.',
    formula: ['P1 = 0.50 × Reach', '   + 0.28 × Permeability', '   + 0.22 × Address'],
    formulaNota: 'If an indicator does not reach its minimum, its weight is shared proportionally among the others.',

    piezas: {
      mapa: 'A map with "us" at the centre and four sentences to try: how each one opens a door, builds a wall or widens the circle.',
      anotado: 'A passage from Pedro Sánchez\'s speech in Barcelona (2026), with every reference to people marked by category.',
      ficha: 'The P1 scorecard for two speeches, Barcelona and the UN, with the calculation step by step.',
      arbol: 'The decision tree for the democratic exception, with the manual\'s example sentences.',
      juego: 'A short game with the manual\'s resolved cases: does it count?',
    },

    que: {
      intro: [
        'Before any argument, language decides who is inside and who is outside. The pronoun places the listener somewhere: inside the speaker\'s circle, on its edge, or facing it.',
        'That placement happens pre-reflectively: listeners feel included or excluded before they think about it.',
      ],
      teoriaTitulo: 'Theoretical basis',
      teoria: [
        { autor: 'Gallese (2001, 2003)', texto: 'Empathy is intersubjective resonance: the shared manifold lets us simulate the other in an embodied, pre-reflective way. The neuroscience of intergroup empathy bias (Xu et al., 2009; Avenanti et al., 2010; Hein et al., 2010) shows that this resonance weakens when the other is categorised as an out-group, and partly recovers when they are individualised or recategorised as "one of us".' },
        { autor: 'Chilton (2004)', texto: 'Discourse builds a deictic space with a centre (I, we, here, now, what is right) and a periphery. Pronominal deixis is an act of political positioning.' },
        { autor: 'Van Dijk (1998, 2006)', texto: 'The ideological square: emphasise our good and their bad.' },
        { autor: 'Mouffe (2005)', texto: 'The legitimate adversary remains inside the common space; the enemy is left outside. Democracy needs a boundary, but an agonistic one, not an antagonistic one.' },
        { autor: 'Laclau (2005)', texto: 'The boundary between "the people" and its other is literal and constitutive. Its opposite pole is often named with abstract words that designate people.' },
        { autor: 'Tajfel and Turner (1979); Gaertner and Dovidio (2000)', texto: 'Categorisation triggers in-group favouritism; recategorisation into a common "us" reduces it.' },
      ],
      cautelaTitulo: 'Caution',
      cautela: 'P1 does not measure the audience\'s neural resonance. It is a discursive indicator of the categorisation conditions that neuroscience associates with that resonance.',
    },

    noMide: {
      cabecera: ['Phenomenon', 'Where it is measured'],
      filas: [
        { fenomeno: 'War verbs ("defeat", "fight")', destino: ['P2', 'P6'], nota: 'metaphor and action' },
        { fenomeno: 'Competition frames ("victory", "battle")', destino: ['P2'] },
        { fenomeno: 'Moral judgement of the adversary ("corrupt", "evil")', destino: ['P3'] },
        { fenomeno: 'Dehumanisation ("plague", "virus")', destino: ['P2', 'P3'], nota: 'in P1 it only counts as one more closure' },
        { fenomeno: 'Emotions mobilised', destino: ['P4'] },
        { fenomeno: 'Coercive actions ("twist their arm")', destino: ['P6'] },
        { fenomeno: 'The speaker\'s "I" (vertical distance from the audience)', destino: ['P8'], nota: 'does not score in P1; candidate for P8' },
      ],
      regla: 'General rule: P1 records where the line is drawn, not what is said about whoever ends up on the other side.',
    },

    aplica: {
      pasos: [
        { nombre: 'Extract', quien: 'Code', texto: 'A script pulls out every reference to people: pronouns, 1st and 2nd person verb endings, possessives and clitics, each with its sentence. It is deterministic: the same text always gives the same table.' },
        { nombre: 'Review', quien: 'Human, 5 minutes', texto: 'The extractor gets about 9 out of 10 right. Typical errors (wrong person assigned, nouns taken for verbs, attached clitics missed, subjects counted twice) are flagged, and omissions are added by hand.' },
        { nombre: 'Classify', quien: 'Human or AI', texto: 'Each reference gets a code from the manual. Boundary events are recorded in a separate table.' },
        { nombre: 'Calculate', quien: 'Code', texto: 'A script applies the formulas and writes the scorecard.' },
      ],
      clave: 'The AI never gives the score: it classifies, and the formulas calculate.',
      reproducibilidad: 'Version 1.1 tested with spaCy 3.8.16 and the es_core_news_md 3.8.0 model. Any change in the software version, the AI model or the manual is noted on the scorecard, because it can change the results.',
    },

    ind: {
      queMide: 'What it measures',
      unidad: 'Unit',
      formula: 'Formula',
      reglas: 'Rules',
      codigo: 'Code',
      categoria: 'Category',
      valor: 'Value',
      ejemplos: 'Examples',
      noCuenta: 'does not count',
      alcance: {
        nombre: 'Reach of "us"',
        peso: '50%',
        queMide: 'How many of the speech\'s "we"s are built against someone.',
        unidad: 'Each first person plural mention (pronoun, verb ending or possessive).',
        codigos: [
          { codigo: 'U', categoria: 'Universal, no opposition', valor: '10', ej: '«nuestros hijos» (our children), «nuestras democracias» (our democracies), «no podemos volver a la situación anterior» (we cannot go back to how things were; said to the whole international community)' },
          { codigo: 'G', categoria: 'Group with no loser', valor: '10', ej: '«en este lugar somos 5.000 personas soñando un mundo mejor» (here we are 5,000 people dreaming of a better world), «estamos aquí para celebrar nuestra unidad» (we are here to celebrate our unity)' },
          { codigo: 'GC', categoria: 'Against someone (group or universal)', valor: '0', ej: '«la vergüenza para ellos; para nosotros el orgullo» (shame for them; pride for us), «vamos a reconstruir lo que ellos han tratado de destruir» (we will rebuild what they tried to destroy), «el pueblo frente a la casta» (the people against the caste), «los tecnoligarcas se llenan el bolsillo a costa de nuestras democracias» (the tech oligarchs line their pockets at the expense of our democracies)' },
          { codigo: 'S', categoria: 'Situational', valor: null, ej: '«los líderes que nos acompañan aquí» (the leaders joining us here)' },
          { codigo: 'I', categoria: 'Institutional', valor: null, ej: '«desde España condenamos» (from Spain we condemn), «estamos aprobando una regularización» (we are approving a regularisation)' },
          { codigo: 'A', categoria: 'Ambiguous', valor: null, ej: 'Cannot be decided with the available context.' },
          { codigo: 'X', categoria: 'Extraction error', valor: null, ej: '' },
          { codigo: 'Y', categoria: 'First person singular ("I", "me", "my")', valor: null, ej: 'Recorded for a future P8.' },
          { codigo: 'F', categoria: 'Third person "they"', valor: null, ej: 'The boundary it marks is recorded as an event under permeability.' },
        ],
        reglas: [
          '"Against someone" overrides reach. Any "we", group or universal, that is built in its sentence against an identifiable other is GC. This is Laclau\'s populist boundary: "the people" against "the caste" is universal in form and exclusionary in function. Only the democratic exception lets it off.',
          'The loser has to be in the text. A "we" is GC only if the other is identifiable: named ("the right") or recoverable from the immediate context ("they", "those who criticise us"). If the loser is only implicit in a metaphor ("this victory is yours"), it is G, and the competitive frame is picked up by P2.',
          'The warm group is inclusive. Speaking to one\'s own without invalidating anyone builds no wall, which is why G is worth the same as U. What sets apart a speech that opens the boundary to the whole of society is captured by permeability.',
          'The sentence is the context. Classification is decided by looking at the sentence containing the mention and, if needed, the previous one.',
          'Situational is the "we" that only points to those physically present. It is neither good nor bad.',
        ],
        formula: 'Reach = 10 × (U + G) / (U + G + GC)',
      },
      interpelacion: {
        nombre: 'Address',
        peso: '22%',
        queMide: 'How the speech addresses its audience in the second person.',
        unidad: 'Each second person mention (tú, usted, ustedes, vosotros; their verb endings, possessives and clitics).',
        codigos: [
          { codigo: '2I', categoria: 'Inclusive', ej: '«gracias por llenar este espacio con vuestra ilusión» (thank you for filling this space with your hope), «os pido que hagamos realidad nuestros sueños» (I ask you to make our dreams come true)' },
          { codigo: '2C', categoria: 'Against someone', ej: '«os pido que no os engañen» (I ask you not to let them fool you; it assumes someone who deceives), «ustedes, los de siempre» (you, the usual crowd)' },
        ],
        regla: 'Warmth towards one\'s own audience is inclusive unless the sentence invalidates or attacks someone else. It is the same logic as reach, democratic exception included.',
        formula: 'Address = 10 × 2I / (2I + 2C)',
      },
      permeabilidad: {
        nombre: 'Permeability',
        peso: '28%',
        queMide: 'Whether the boundary is a wall or a door: whether the other can become part of "us".',
        unidad: 'The boundary event: each sentence in which the speech places an identifiable human other in relation to "us". A sentence with two different referents generates two events. The same referent with several marks in the same sentence is a single event.',
        blancosTitulo: 'Who is left outside? Types of target',
        blancosCabecera: ['Target', 'Example', 'Is it a boundary?'],
        blancos: [
          { blanco: 'A problem', ej: '"ending poverty", "corruption"', frontera: 'No', es: false },
          { blanco: 'A policy', ej: '"this labour reform is unfair"', frontera: 'No', es: false },
          { blanco: 'An ideology', ej: '"neoliberalism has failed"', frontera: 'Only if it is given a body: presented as a hostile agent ("communism wants to destroy your families") or extended to its bearers', es: null },
          { blanco: 'People with a structural name', ej: '"the caste", "the elites", "the regime", "those at the top"', frontera: 'Yes', es: true },
          { blanco: 'The common house (democratic institutions)', ej: '"the judges are coup plotters", "the elections are rigged"', frontera: 'Yes. Criticising how an institution works ("justice is slow") is not; delegitimising it is', es: true },
        ],
        marcasTitulo: 'Closure and opening marks',
        marcasNota: 'Every mark is worth 1.',
        cierresTitulo: 'Closures (C) · 7 marks',
        cierres: [
          ['C1', 'Us/them contrast', '"shame for them; pride for us"'],
          ['C2', 'Homogeneous bloc', '"they are all the same", a list of behaviours fused into a single "them"'],
          ['C3', 'Irreversibility', '"that\'s how they are and they won\'t change", "they will never be one of us"'],
          ['C4', 'Expulsion from the community', '"they are not the people", "anti-Spanish"'],
          ['C5', 'Threat aimed at "us"', '"they are coming for us", "they have tried to make us ashamed"'],
          ['C6', 'Dehumanisation', '"a plague", "rats"'],
          ['C7', 'Denial of voice', '"you don\'t talk to those people"'],
        ],
        aperturasTitulo: 'Openings (A) · 9 marks',
        aperturas: [
          ['A1', 'Invitation', '"also to those who did not vote for us"'],
          ['A2', 'Separating leaders from people', 'distinguishing a government\'s decision from its people'],
          ['A3', 'Common belonging with difference', '"we think differently, but they belong here too", "they are us"'],
          ['A4', 'Legitimate adversary', '"I respect those who defend another option"'],
          ['A5', 'Humanising someone on the other side', 'naming a specific person with their story'],
          ['A6', 'Acknowledging a success or self-criticism', '"they got that right", "we were wrong too"'],
          ['A7', 'Shared fate', '"this affects all of us, whatever we think"'],
          ['A8', 'Denying a closure', '"they are not enemies"'],
          ['A9', 'Conditional inclusion', '"those who change course will be welcome"'],
        ],
        dificilesTitulo: 'Hard cases',
        dificiles: [
          ['Reported speech', '"They say we are anti-Spanish" is not a closure by the speaker. If the speaker explicitly rejects it, it may be A8.'],
          ['Irony', 'It is coded according to the clear intention of the context; if in doubt, it is not coded.'],
          ['Mixed mark', '"Their leaders betrayed us, but their voters are honest people" is two events: a closure (leaders) and an A2 opening (voters).'],
          ['Addressing the adversary', '"I want to tell the right..." is not a closure in itself: it speaks to them, it does not expel them. What it says about them is measured by P3.'],
        ],
        formula: 'Permeability = 10 × (A + 1) / (A + C + 2)',
        formulaNombre: 'Laplace\'s rule of succession',
        formulaNota: 'With no events, permeability is not scored. With few events, the formula pulls the score towards the centre so that a single event cannot send it flying.',
      },
    },

    excepcion: {
      intro: 'The IRA is against violence, not against whoever names it. A boundary drawn against someone because of their violent or anti-democratic conduct is not penalised: under permeability it is recorded as CP and does not score; under reach and address, the "we" or the second person keeps its normal category (U, G, 2I) with the note "democratic exception".',
      verdad: 'The IRA does not decide whether the accusation is true. That is why the exception depends on how the boundary is drawn, not on who is right. It only applies if the sentence meets all three conditions:',
      condiciones: [
        ['Specific conduct', 'The other is identified by an act ("attacked", "invaded", "murdered", "annulled the elections"), not by what they are.'],
        ['Bounded agent', 'The act is attributed to whoever committed it: a person, a government, an armed group, "those who did this". Never to a people, an ethnic group, a religion or a party\'s voters.'],
        ['No extension', 'The sentence does not generalise ("all", "always"), essentialise ("that\'s what they are") or dehumanise.'],
      ],
      falla: 'If any condition fails, it is a normal closure (and the "we" is GC).',
      ejemplosCabecera: ['Sentence', 'Exception?'],
      ejemplos: [
        ['"The terrorist attacked our community"', true, 'specific act, individual agent'],
        ['"Russia has invaded our country"', true, 'specific act, the State as actor'],
        ['"The Kyiv regime attacked our people"', true, 'formally identical to the previous one'],
        ['"The government of X is committing genocide"', true, 'bounded agent'],
        ['"The X are genocidal"', false, 'an entire people'],
        ['"Ukrainians are Nazis who hate us"', false, 'an entire people, essentialised'],
        ['"Immigrants bring violence to our neighbourhoods"', false, 'it talks about violence, but against a group for what it is'],
        ['"We will not make deals with anyone who justifies violence"', true, 'applies to anyone, including one\'s own side'],
      ],
      si: 'Yes', no: 'No',
      salvaguardasTitulo: 'Two safeguards',
      salvaguardas: [
        ['Warning on the scorecard', 'Every exception applied is listed on the scorecard with its sentence, under the warning "the IRA does not verify these accusations", so readers know where the analysis has relied on the speaker\'s word.'],
        ['Withdrawal after a documented debunk', 'If an independent, published fact-check (a verifier accredited by the IFCN network, such as Maldita, Newtral or EFE Verifica) debunks the accusation, the exception is withdrawn and the sentence counts as a normal closure: inventing an aggressor to draw a boundary is manufacturing an enemy. The source is cited on the scorecard. Without a documented debunk, the exception stands with its warning.'],
      ],
    },

    minimos: {
      cabecera: ['Indicator', 'Weight', 'Minimum to score'],
      filas: [
        ['Reach', '50%', '15 classifiable "we"s (U + G + GC)'],
        ['Permeability', '28%', '3 events (A + C)'],
        ['Address', '22%', '3 mentions (2I + 2C)'],
      ],
      notas: [
        'If an indicator does not reach its minimum, its weight is shared proportionally among the others.',
        'P1 is scored if reach or permeability reaches its minimum. That way, a speech that polarises almost entirely in the third person ("they steal, they lie") still gets a score: mostly from permeability.',
        'P1 robustness. If reach meets its minimum: 15 to 40 classifiable "we"s, indicative; more than 40, solid. If only permeability scores: 3 to 5 events, indicative; 6 or more, solid. If neither does: not scored.',
        'Repetitions. Every mention and every event counts, even when repeated, and the same sentence can subtract in both reach and permeability: each indicator measures a different property of the sentence.',
        'The minimum length is expressed in references, not words: a rally speech may have 40 "we"s per thousand words and an institutional address, 14.',
      ],
    },

    limites: [
      ['"Ustedes" in the Americas', 'It is grammatically third person and the extractor only looks for 1st and 2nd. It must be added before analysing the Latin American corpus. "Les" is also ambiguous.'],
      ['The named adversary', 'The extractor only catches "ellos" (they); noun phrases ("the right", "the tech oligarchs") and implicit subjects ("have tried to...") are found by the coder when annotating events. Pending: proposing them automatically.'],
      ['Well-phrased false accusations', 'A false accusation of violence that meets the exception\'s three conditions passes the filter until there is a documented debunk. The IRA measures language, not facts; the scorecard says so, and verification is a job for journalism.'],
      ['Speeches with few but intense events', 'The UN speech has two clear closures ("people without scruples, activists of lies") and remains unscored because of the minimum of 3.'],
      ['Translations', 'P1 is not applied to translated speeches: the pronoun is chosen by the translator. English would need its own extractor.'],
      ['Discourse genre', 'Rally, institutional address, interview and social media should be recorded so comparisons are made within the same genre.'],
      ['Weights and intensities', 'The weights (50/28/22) and the value of 1 for every mark are hypotheses: they will be calibrated with the corpus.'],
      ['Reliability', 'The inter-coder study (Krippendorff\'s α ≥ 0.80 on codes and events) and the human versus AI comparison are still missing.'],
      ['Overlap between indicators', 'If, with more speeches, reach and permeability always moved together, one of them would be redundant and P1 could be simplified. It is not an error, but a possible future simplification.'],
    ],

    cambios: {
      fecha: '9 October 2026',
      v1: {
        titulo: 'Version 1',
        decisiones: [
          'P1 becomes purely deictic: the verbs accompanying the pronoun leave P1 (they go to P2 and P6).',
          'Counting by code (spaCy and a fixed lexicon) and classification by a human or AI; the calculation, always by code.',
          'Robustness thresholds: fewer than 15 "we"s, unreliable; 15 to 40, indicative; more than 40, solid.',
          'The group "we" with no loser is worth 10, the same as the universal one; only the "we" against someone is worth 0.',
          'A loser implicit in a metaphor does not turn the "we" into "against someone": P2 measures it.',
          'New situational category, outside the calculation.',
          'The "I" leaves P1; candidate for P8 once it can be coded with observable marks.',
          'Address: warmth towards one\'s own audience is inclusive unless it attacks or invalidates someone else.',
          'Permeability based on observable events; Laplace formula; minimum of 3 events.',
          'Types of target: problems and policies are not boundaries; ideologies only when given a body; people with a structural name and delegitimising the common house, yes.',
          'Democratic exception: a boundary drawn because of violent or anti-democratic conduct does not score.',
          'All closure and opening marks are worth 1 in this version.',
        ],
      },
      v11: {
        titulo: 'Version 1.1',
        decisiones: [
          '"Against someone" overrides reach: the universal "we" built against an identifiable other is GC.',
          'P1 is scored if reach or permeability reaches its minimum.',
          'Repetitions and sentences that subtract in two indicators count every time: each indicator measures a different property.',
          'The democratic exception applies to all of P1, with three conditions (specific conduct, bounded agent, no extension) that do not depend on whether the accusation is true.',
          'Every exception is flagged on the scorecard; it is withdrawn if an accredited fact-checker debunks it with a published source.',
        ],
      },
    },

    referencias: REFERENCIAS,
    manual: 'Full P1 manual in the repository',
    pie: { volver: '← Back to the index', siguiente: 'Next: P2 · coming soon' },
  },
};
